name: Create or Update Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "The name of the repository to create."
        required: true
        type: string
      is_public_repo:
        description: "Whether to make the repository public or private. If unchecked, repo is private."
        required: true
        default: true
        type: boolean
      package_import_name:
        description: "The name of the package to import in the generated project."
        required: true
        type: string
# Test
env:
  GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

jobs:
  create-repo-if-not-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "kanitvural"
      - name: Set environment variables
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: kanitvural
          IS_PUBLIC_REPO: ${{ github.event.inputs.is_public_repo }}
        run: |
            bash run.sh create-repo-if-not-exists

  configure-repo:
    needs: create-repo-if-not-exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "kanitvural"
      - name: Set environment variables
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: kanitvural
        run: |
            bash run.sh configure-repo

  open-pr-with-generated-project:
    needs: create-repo-if-not-exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "kanitvural"
      - name: Set environment variables
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package_import_name }}
          GITHUB_USERNAME: kanitvural
        run: |
            bash run.sh open-pr-with-generated-project
